### ISSUE TITLE
GoogleFrog Local Todo

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/Hunted#15]
- [x] Make Burrow Spawner.
- [x] Make Rabbits a bit scared of the flashlight.
- [x] Make Flashlight tower which causes a bit of fear as well.
- [x] Make structure/mine placement.
- [x] Make Wave structure (placement phase, fighting phase) and recurrent waves.

**Comment by gajop** [comment]
So to write here as well:
Burrow spawner should just make a single random spawn at the start of the game and progressively add more burrows as time goes on up to about 10 or so.
Make Rabbits a bit scared of the flashlight. -> Agreed
Make Flashlight tower which causes a bit of fear as well. -> Would be _very cool_ to have imo, have those automatically place near the corners of the carrot fields.
Make structure/mine placement. -> Drop this and instead have right click to shoot grenades/mines/traps. I can code this.
Make Wave structure (placement phase, fighting phase) and recurrent waves. -> Drop the wave structure. I actually think game will be more fun if you have a constant influx of rabbits

**Comment by GoogleFrog** [comment]
Burrow spawner is sufficiently done. I don't think random spawn will get good results. I just hardcoded 5 burrow locations into the spawn handler. It should be easy to set them up on the eventual map.

Wave structure is in.

**Comment by GoogleFrog** [comment]
Rabbits fear the flashlight. Often it makes them speed up a bit and change their path. If the flashlight is in their way they can turn and run away. It is a decent bit of extra interaction to put the player in the world.
